### PR TITLE
IND-68: replace terraform pre-commit repo

### PR DESCRIPTION
**Pull request by res0nat0r**
- The existing terraform pre-commit repo being used is very old and outdated. 

The current repo runs the command: `terraform validate -check-variables=false`
https://github.com/kintoandar/pre-commit/blob/master/bin/tf_validate.sh#L14

`-check variables=false` does not exist anymore. This appears to be an extremely old option that existed in previous versions of Terraform that isn't used anymore. The file linked above was committed in August 2017, so it is already 5+ years old.

The author has said as of 6 days ago he hasn't maintained this and is going to archive the repo soon: https://github.com/kintoandar/pre-commit/issues/10

---

There is a well maintained repo with 2k stars here: https://github.com/antonbabenko/pre-commit-terraform

The maintainer of this repo is the primary author of many/most of the AWS Terraform modules so this is likely the best place to switch to. It also works as a drop-in replacement. This PR only swaps out the repo url and version, and `pre-commit install` will work and the terraform checks will work again automagically.

Also this repo looks to support a lot of other cool stuff we could use in the future too:

[checkov](https://github.com/bridgecrewio/checkov) required for checkov hook.
[terraform-docs](https://github.com/terraform-docs/terraform-docs) required for terraform_docs hook.
[terragrunt](https://terragrunt.gruntwork.io/docs/getting-started/install/) required for terragrunt_validate hook.
[terrascan](https://github.com/tenable/terrascan) required for terrascan hook.
[TFLint](https://github.com/terraform-linters/tflint) required for terraform_tflint hook.
[TFSec](https://github.com/liamg/tfsec) required for terraform_tfsec hook.
[infracost](https://github.com/infracost/infracost) required for infracost_breakdown hook.
[jq](https://github.com/stedolan/jq) required for infracost_breakdown hook.
[tfupdate](https://github.com/minamijoyo/tfupdate) required for tfupdate hook.
[hcledit](https://github.com/minamijoyo/hcledit) required for terraform_wrapper_module_for_each hook.

https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies

### CODE REVIEW

**Comment by wright-nexient** [comment]
Does this replaced plugin now cause 

terraform_validate to work? In past it broke commits

terraform_fmt works though.

**Comment by res0nat0r** [comment]
> Does this replaced plugin now cause
> 
> terraform_validate to work? In past it broke commits
> 
> terraform_fmt works though.

Yep! :godmode:

**Comment by cwright-gia** [comment]
> Does this replaced plugin now cause
> 
> terraform_validate to work? In past it broke commits
> 
> terraform_fmt works though.

scratch that... All looks good. Your detailed reasoning and explanation gave insight into the fix.

**Comment by cjharries-nexient** [comment]
This fixes #19

**Review by cjharries-nexient — APPROVED** [review]

**Comment by res0nat0r** [comment]
Also fixes #18

**Review by TheFynx — APPROVED** [review]

**Review by wright-nexient — APPROVED** [review]

**Pull request merged**
